<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

</Project>
